name: Azure Federated Credentials Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # OBLIGATORIO para OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure with Federated Credentials
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: List resource groups
        run: |
          az group list -o table

      - name: List storage accounts in federatedcreds-rg
        run: |
          az storage account list \
            --resource-group federatedcreds-rg \
            -o table
